# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\"\x1e\n\x06\x41\x64\x64Req\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"-\n\x06\x41\x64\x64Rsp\x12\x0b\n\x03res\x18\x01 \x01(\x05\x12\x16\n\x0eserver_message\x18\x02 \x01(\t2)\n\x0e\x45xampleService\x12\x17\n\x03\x41\x64\x64\x12\x07.AddReq\x1a\x07.AddRspb\x06proto3')



_ADDREQ = DESCRIPTOR.message_types_by_name['AddReq']
_ADDRSP = DESCRIPTOR.message_types_by_name['AddRsp']
AddReq = _reflection.GeneratedProtocolMessageType('AddReq', (_message.Message,), {
  'DESCRIPTOR' : _ADDREQ,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:AddReq)
  })
_sym_db.RegisterMessage(AddReq)

AddRsp = _reflection.GeneratedProtocolMessageType('AddRsp', (_message.Message,), {
  'DESCRIPTOR' : _ADDRSP,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:AddRsp)
  })
_sym_db.RegisterMessage(AddRsp)

_EXAMPLESERVICE = DESCRIPTOR.services_by_name['ExampleService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDREQ._serialized_start=17
  _ADDREQ._serialized_end=47
  _ADDRSP._serialized_start=49
  _ADDRSP._serialized_end=94
  _EXAMPLESERVICE._serialized_start=96
  _EXAMPLESERVICE._serialized_end=137
# @@protoc_insertion_point(module_scope)
